# Generated by Django 5.2.8 on 2025-12-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominvitation',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
