# Generated by Django 5.2.7 on 2025-11-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_answer_attempt_answer_question_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomquizassignment',
            unique_together={('room', 'quiz')},
        ),
    ]
