# Generated by Django 5.2.8 on 2025-12-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text',
            field=models.TextField(blank=True, default='', help_text='...'),
        ),
    ]
