# Generated by Django 5.2.8 on 2025-12-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_correct_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'ตัวเลือก'), ('short', 'คำตอบสั้น ๆ')], max_length=20),
        ),
    ]
